name: flutter_morsedecoder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  flutter:
    sdk: flutter
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
